server:
  port: 11000
  servlet:
    context-path: /ad-search

spring:
  application:
    name: ad-search
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true
    open-in-view: false
  datasource:
    url: jdbc:mysql://114.67.108.221:3306/imooc_ad_data?autoReconnect=true
    username: root
    password: 123456
#    tomcat:
#      max-active: 4
#      min-idle: 2
#      initial-size: 2
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    listener:
      concurrency: 4

eureka:
  client:
    service-url:
      defaultZone: http://114.67.108.221:10000/eureka/

feign:
  hystrix:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

adconf:
  mysql:
    host: 127.0.0.1
    port: 3306
    username: root
    password: Djangobbs
    binlogName: binlog.000038
    position: 60451

  kafka:
    topic: ad-search-mysql-data
